language: objective-c
osx_image: xcode7.1

before_install:
- brew update
- brew uninstall xctool --force
- brew install xctool --HEAD
- brew install carthage
- carthage update --platform iOS
- gem install --no-rdoc --no-ri xcpretty
- xcrun instruments -w "iPhone 6 (9.1 Simulator)" || echo "(Pre)Launched the simulator."

script: 
set -o pipefail && xcodebuild -project RealmResultsController.xcodeproj -scheme RealmResultsController-iOS -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.1' -configuration Debug -sdk iphonesimulator9.1 ONLY_ACTIVE_ARCH=NO test | xcpretty -tc --no-utf
